services:
  redactedhook:
    container_name: redactedhook
    image: ghcr.io/s0up4200/redactedhook:latest
    #build:
      #context: .
      #dockerfile: Dockerfile
    #runtime: runsc-ptrace
    #network_mode: bridge
    user: nobody
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    environment:
      - REDACTEDHOOK__HOST=0.0.0.0 # binds to 127.0.0.1 by default
      - REDACTEDHOOK__PORT=42135 # defaults to 42135
      - TZ=UTC
    ports:
      - 127.0.0.1:42135:42135
    volumes:
      - ./:/redactedhook
    restart: unless-stopped
