services:
  redactedhook:
    container_name: redactedhook
    image: ghcr.io/s0up4200/redactedhook:latest
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    #runtime: runsc-ptrace
    #network_mode: bridge
    user: nobody
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    environment:
      #- REDACTEDHOOK__HOST=127.0.0.1     # Override the host from config.toml
      #- REDACTEDHOOK__PORT=42135         # Override the port from config.toml
      #- REDACTEDHOOK__API_TOKEN=         # Override the API token from config.toml
      #- REDACTEDHOOK__RED_APIKEY=        # Override the red api_key from config.toml
      #- REDACTEDHOOK__OPS_APIKEY=        # Override the ops api_key from config.toml
      - TZ=UTC
    ports:
      - 127.0.0.1:42135:42135
    volumes:
      - ./:/redactedhook
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/usr/local/bin/redactedhook", "health"]
      interval: 30s
      timeout: 10s
      retries: 3
