name: Release

on:
  push:
    tags:
      - '*'
  pull_request:
    branches:
      - main
      - develop

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.1

      #- name: Run tests
      #  run: go test ./...

      - name: Build Docker image
        if: github.event_name == 'pull_request'
        run: docker build -t ghcr.io/s0up4200/redactedhook:${{ github.sha }} .

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GORELEASER_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Run Goreleaser
        uses: goreleaser/goreleaser-action@v2
        if: github.event_name == 'push'
        with:
          version: latest
          args: --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_TOKEN }}